apiVersion: apps/v1
kind: Deployment
metadata:
  name: scaletestapp # ИмяDeployment
spec:
  selector:
    matchLabels:
      app: scaletestapp
  replicas: 1
  template:
    metadata:
      labels:
        app: scaletestapp # Метка для пода, должна совпадать с selector
    spec:
      containers:
      - name: scaletestapp-pod
        image: ghcr.io/yandex-practicum/scaletestapp:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "30Mi"   # гарантироваое количество памяти (100 MiB)
          limits:
            memory: "30Mi"   # максимальный лимит памяти (200 MiB)
